/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Input.h
**     Project     : ECE 594 Project_Group 1
**     Processor   : MCF51EM256CLL
**     Component   : KBI
**     Version     : Component 01.096, Driver 01.25, CPU db: 3.00.060
**     Compiler    : CodeWarrior ColdFireV1 C Compiler
**     Date/Time   : 2021-11-21, 15:06, # CodeGen: 29
**     Abstract    :
**         This component "KBI" implements the Freescale Keyboard 
**         Interrupt Module (KBI/KBD) which allows to catch events 
**         on selected external pins. These pins share one KBI/KBD 
**         interrupt which can be caused by events on the pins.
**     Settings    :
**         Keyboard                    : KBI1 
**         Used pins           
**         Pin 0                       : PTB6_RGPIO14_KBI1P4_TMRCLK1_AD14
**         Pin 1                       : PTB7_RGPIO15_KBI1P5_TMRCLK2_AD15
**         Pin 2                       : PTB1_RGPIO9_KBI1P1_SS3_TX2
**         Pin 3                       : PTB3_RGPIO11_KBI1P3_PRACMP2P1_TX1
**         Pull resistor               : off
**         Generate interrupt on       : falling
**         Interrupt service           : Enabled
**         Interrupt                   : Vkbi1
**         Interrupt Priority          : 220
**         Enable in init. code        : Yes
**         Events enabled in init.     : Yes
**     Contents    :
**         GetVal  - byte Input_GetVal(void);
**         SetEdge - byte Input_SetEdge(byte edge);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Input.h
** @version 01.25
** @brief
**         This component "KBI" implements the Freescale Keyboard 
**         Interrupt Module (KBI/KBD) which allows to catch events 
**         on selected external pins. These pins share one KBI/KBD 
**         interrupt which can be caused by events on the pins.
*/         
/*!
**  @addtogroup Input_module Input module documentation
**  @{
*/         

#ifndef __Input
#define __Input

/*Include shared modules, which are used for whole project*/
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"

/* MODULE Input. */

#include "Cpu.h"

/* PUBLISHED CONSTANTS for using together with GetVal method  */
#define Input_NUM_PIN0        0x01U /* Mask of Pin0 */
#define Input_NUM_PIN1        0x02U /* Mask of Pin1 */
#define Input_NUM_PIN2        0x04U /* Mask of Pin2 */
#define Input_NUM_PIN3        0x08U /* Mask of Pin3 */

/* PUBLISHED CONSTANTS for enabled pins */
#define Input_PIN_SIGNAL0     0x40U  /* Mask of Pin0*/
#define Input_PIN_SIGNAL1     0x80U  /* Mask of Pin1*/
#define Input_PIN_SIGNAL2     0x02U  /* Mask of Pin2*/
#define Input_PIN_SIGNAL3     0x08U  /* Mask of Pin3*/

/* Deprecated */
#define PinSignal0            0x01U
#define PinSignal1            0x02U
#define PinSignal2            0x04U
#define PinSignal3            0x08U


void Input_Init(void);
/*
** ===================================================================
**     Method      :  Input_Init (component KBI)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

__interrupt void Input_Interrupt(void);
/*
** ===================================================================
**     Method      :  Input_Interrupt (component KBI)
**
**     Description :
**         The method services the interrupt of the selected peripheral(s)
**         and eventually invokes event(s) of the component.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/

byte Input_GetVal(void);

/*
** ===================================================================
**     Method      :  Input_GetVal (component KBI)
**     Description :
**         Returns the value of pins
**     Parameters  : None
**     Returns     :
**         ---             - The value of associated pins (bits ordered
**                           according to the component list of pins)
** ===================================================================
*/

byte Input_SetEdge(byte edge);
/*
** ===================================================================
**     Method      :  Input_SetEdge (component KBI)
**     Description :
**         Sets the sensitive edge. If all selected pins don't have the
**         same edge setting possibility, the method allows to set only
**         those edges that are common (possible to set for all
**         selected pins).
**     Parameters  :
**         NAME            - DESCRIPTION
**         edge            - Edge type:
**                           0 - falling edge
**                           1 - rising edge
**                           2 - both edges
**                           3 - low level
**                           4 - high level
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_RANGE - Value is out of range
** ===================================================================
*/


/* END Input. */

#endif /* ifndef __Input */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale ColdFireV1 series of microcontrollers.
**
** ###################################################################
*/
