/* ###################################################################
**     THIS COMPONENT MODULE IS GENERATED BY THE TOOL. DO NOT MODIFY IT.
**     Filename    : Input.c
**     Project     : ECE 594 Project_Group 1
**     Processor   : MCF51EM256CLL
**     Component   : KBI
**     Version     : Component 01.096, Driver 01.25, CPU db: 3.00.060
**     Compiler    : CodeWarrior ColdFireV1 C Compiler
**     Date/Time   : 2021-11-21, 15:06, # CodeGen: 29
**     Abstract    :
**         This component "KBI" implements the Freescale Keyboard 
**         Interrupt Module (KBI/KBD) which allows to catch events 
**         on selected external pins. These pins share one KBI/KBD 
**         interrupt which can be caused by events on the pins.
**     Settings    :
**         Keyboard                    : KBI1 
**         Used pins           
**         Pin 0                       : PTB6_RGPIO14_KBI1P4_TMRCLK1_AD14
**         Pin 1                       : PTB7_RGPIO15_KBI1P5_TMRCLK2_AD15
**         Pin 2                       : PTB1_RGPIO9_KBI1P1_SS3_TX2
**         Pin 3                       : PTB3_RGPIO11_KBI1P3_PRACMP2P1_TX1
**         Pull resistor               : off
**         Generate interrupt on       : falling
**         Interrupt service           : Enabled
**         Interrupt                   : Vkbi1
**         Interrupt Priority          : 220
**         Enable in init. code        : Yes
**         Events enabled in init.     : Yes
**     Contents    :
**         GetVal  - byte Input_GetVal(void);
**         SetEdge - byte Input_SetEdge(byte edge);
**
**     Copyright : 1997 - 2014 Freescale Semiconductor, Inc. 
**     All Rights Reserved.
**     
**     Redistribution and use in source and binary forms, with or without modification,
**     are permitted provided that the following conditions are met:
**     
**     o Redistributions of source code must retain the above copyright notice, this list
**       of conditions and the following disclaimer.
**     
**     o Redistributions in binary form must reproduce the above copyright notice, this
**       list of conditions and the following disclaimer in the documentation and/or
**       other materials provided with the distribution.
**     
**     o Neither the name of Freescale Semiconductor, Inc. nor the names of its
**       contributors may be used to endorse or promote products derived from this
**       software without specific prior written permission.
**     
**     THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**     ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**     WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**     DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**     ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**     (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**     LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**     ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**     (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**     SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
**     
**     http: www.freescale.com
**     mail: support@freescale.com
** ###################################################################*/
/*!
** @file Input.c
** @version 01.25
** @brief
**         This component "KBI" implements the Freescale Keyboard 
**         Interrupt Module (KBI/KBD) which allows to catch events 
**         on selected external pins. These pins share one KBI/KBD 
**         interrupt which can be caused by events on the pins.
*/         
/*!
**  @addtogroup Input_module Input module documentation
**  @{
*/         

/* MODULE Input. */

#include "Events.h"
#include "Input.h"



/*
** ===================================================================
**     Event       :  Input_OnInterrupt (module Events)
**
**     Component   :  Input [KBI]
**     Description :
**         This event is called when the active signal edge/level
**         occurs. This event is enabled only if <Interrupt
**         service/event> property is enabled.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
ISR(Input_Interrupt)
{
  KBI1SC_KBACK = 0x01U;                /* Clear the interrupt flag */
  Input_OnInterrupt();                 /* Invoke user event */
}

/*
** ===================================================================
**     Method      :  Input_GetVal (component KBI)
**     Description :
**         Returns the value of pins
**     Parameters  : None
**     Returns     :
**         ---             - The value of associated pins (bits ordered
**                           according to the component list of pins)
** ===================================================================
*/
byte Input_GetVal(void)
{
  byte value = 0x00U;
  value |= ((PTBD & 0x40U) >> 6);
  value |= ((PTBD & 0x80U) >> 6);
  value |= (byte)((PTBD & 0x02U) << 1);
  value |= PTBD & 0x08U;
  return value;
}

/*
** ===================================================================
**     Method      :  Input_SetEdge (component KBI)
**     Description :
**         Sets the sensitive edge. If all selected pins don't have the
**         same edge setting possibility, the method allows to set only
**         those edges that are common (possible to set for all
**         selected pins).
**     Parameters  :
**         NAME            - DESCRIPTION
**         edge            - Edge type:
**                           0 - falling edge
**                           1 - rising edge
**                           2 - both edges
**                           3 - low level
**                           4 - high level
**     Returns     :
**         ---             - Error code, possible codes:
**                           ERR_OK - OK
**                           ERR_RANGE - Value is out of range
** ===================================================================
*/
byte Input_SetEdge(byte edge)
{
  if ((edge > 4U) || (edge == 2U)) {   /* If parameter is out of range */
    return ERR_RANGE;                  /* ....then return error */
  }
  KBI1SC_KBIE = 0U;                    /* Disable device */
  if ((edge == 3U) || (edge == 4U)) {  /* Level selected */
    KBI1SC_KBIMOD = 0x01U;             /* Set the level */
    if (edge == 3U) {
    /* KBI1ES: KBEDG5=0,KBEDG4=0,KBEDG3=0,KBEDG1=0 */
      KBI1ES &= (byte)(~(byte)0x3AU);  /* The low level */
    }
    else {
    /* KBI1ES: KBEDG5=1,KBEDG4=1,KBEDG3=1,KBEDG1=1 */
      KBI1ES |= 0x3AU;                 /* The high level */
    }
  }
  else {                               /* Edge selected */
    KBI1SC_KBIMOD = 0U;                /* Set the edge */
    if (edge == 0U) {
    /* KBI1ES: KBEDG5=0,KBEDG4=0,KBEDG3=0,KBEDG1=0 */
      KBI1ES &= (byte)(~(byte)0x3AU);  /* The falling edge */
    }
    else {
    /* KBI1ES: KBEDG5=1,KBEDG4=1,KBEDG3=1,KBEDG1=1 */
      KBI1ES |= 0x3AU;                 /* The rising edge */
    }
  }
  KBI1SC_KBACK = 0x01U;                /* Clear the interrupt flag */
  KBI1SC_KBIE = 0x01U;                 /* Enable device */
  return ERR_OK;
}

/*
** ===================================================================
**     Method      :  Input_Init (component KBI)
**
**     Description :
**         Initializes the associated peripheral(s) and the component 
**         internal variables. The method is called automatically as a 
**         part of the application initialization code.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void Input_Init(void)
{
  /* KBI1ES: KBEDG7=0,KBEDG6=0,KBEDG5=0,KBEDG4=0,KBEDG3=0,KBEDG2=0,KBEDG1=0,KBEDG0=0 */
  setReg8(KBI1ES, 0x00U);               
  /* KBI1SC: ??=0,??=0,??=0,??=0,KBF=0,KBACK=0,KBIE=0,KBIMOD=0 */
  setReg8(KBI1SC, 0x00U);               
  /* KBI1PE: KBIPE5=1,KBIPE4=1,KBIPE3=1,KBIPE1=1 */
  setReg8Bits(KBI1PE, 0x3AU);          /* Enable appropriate interrupt pin(s) */ 
  /* KBI1SC: KBACK=1 */
  setReg8Bits(KBI1SC, 0x04U);          /* Clear the interrupt flag */ 
  /* KBI1SC: KBIE=1 */
  setReg8Bits(KBI1SC, 0x02U);          /* Enable interrupts */ 
}

/* END Input. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.3 [05.09]
**     for the Freescale ColdFireV1 series of microcontrollers.
**
** ###################################################################
*/
